apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend
spec:
  hard:
    pods: "3"
    requests.cpu: "1000m"
    limits.cpu: "1000m"
    requests.memory: "1Gi"
    limits.memory: "1Gi"
---

apiVersion: v1
kind: LimitRange
metadata:
  name: backend-limits
  namespace: backend
spec:
  limits:
  - default:
      cpu: "250m"
      memory: "256Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
