apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend
spec:
  hard:
    pods: "10"
    requests.cpu: "1000m"
    limits.cpu: "1000m"
    requests.memory: "1.5Gi"
    limits.memory: "1.5Gi"
---

apiVersion: v1
kind: LimitRange
metadata:
  name: frontend-limits
  namespace: frontend
spec:
  limits:
  - default:
      cpu: "100m"
      memory: "140Mi"
    defaultRequest:
      cpu: "100m"
      memory: "140Mi"
    type: Container
